M48
; DRILL file {KiCad (6.0.5)} date Wed Dec 28 23:50:46 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-28T23:50:46+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X4.1465Y-2.1291
X4.1465Y-3.0346
X6.4299Y-2.1291
X6.4299Y-3.0346
T0
M30
